# Generated by Django 5.1.5 on 2025-01-19 00:00

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default=backend.models.generate_session_name, max_length=5, unique=True)),
                ('player_one_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player_two_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
