# Generated by Django 4.2.18 on 2025-01-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='prompt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
