# Generated by Django 5.1.5 on 2025-01-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='player_one_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='player_two_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
