# Generated by Django 4.2.18 on 2025-01-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_session_player_one_score_session_player_two_score_and_more'),
        ('backend', '0002_session_prompt'),
    ]

    operations = [
    ]
