# Generated by Django 4.2.18 on 2025-01-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_merge_20250119_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='prompt_guess',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
