# Generated by Django 4.2.18 on 2025-01-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_session_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='selected_image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
