# Generated by Django 5.1.5 on 2025-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_session_selected_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='styled_prompt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='styled_prompt_guess',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
